### PR TITLE
fix block_entities example

### LINKED ISSUE #389: Fix block_entities example
## Valence Version

0f3e6f2b7f0ace1f0a11ef9f5d908c9ddc2bbcf5

## What You Did

I tried to run the [block_entities](https://github.com/valence-rs/valence/blob/main/examples/block_entities.rs) example.

## What Went Wrong

 I realized that the sign is not working. It's supposed to update its text when a message is sent in the chat, but it remains empty.

## Additional Information

**This is due to the fact that Minecraft 1.20 has changed how the NBT format of signs works.**
https://minecraft.fandom.com/wiki/Sign#Block_data
image

### PR DESCRIPTION
**Pull request by dyc3**
## Description

fixes #389

### CODE REVIEW

**Comment by Bafbi** [comment]
I test it and it doen't work.
```rust
    let sign = Block::with_nbt(
        BlockState::OAK_SIGN.set(PropName::Rotation, PropValue::_0),
        compound! {
            "is_waxed" => true,
            "front_text" => compound! {
                "messages" => List::String(vec![
                    "Type in chat:".color(Color::RED).to_string(),
                ]),
            }
        },
    );
```
The nbt that the client have
image

**Comment by dyc3** [comment]
Maybe it needs to have all 4 rows?

**Comment by Bafbi** [comment]
and using to_string on text don't convert to json

**Comment by pepperoni21** [comment]
> I test it and it doen't work.
> 
> ```rust
>     let sign = Block::with_nbt(
>         BlockState::OAK_SIGN.set(PropName::Rotation, PropValue::_0),
>         compound! {
>             "is_waxed" => true,
>             "front_text" => compound! {
>                 "messages" => List::String(vec![
>                     "Type in chat:".color(Color::RED).to_string(),
>                 ]),
>             }
>         },
>     );
> ```
> 
> The nbt that the client have image

And if you try to merge the data after spawning the sign? It's probably a valence_nbt issue though

**Comment by dyc3** [comment]
I managed to figure it out. All 4 lines in `messages` are required, and they must all be rendered `Text`, even if blank.

github is currently experiencing on outage related to pull requests, so the commit isn't showing up here right now, but the branch has been updated.

**Comment by rj00a** [comment]
Made some adjustments to `Text`. In particular, I removed the weird custom `Debug`/`Display` impl and just convert to JSON there.

Also enabled online mode in the example so that right clicking the skull functions correctly.

**Pull request merged**
