### PR TITLE
Client Component Division

### LINKED ISSUE #199: Dividing Clients and Entities into smaller components
Brainstorming some ideas for how the monolithic `Client` and `McEntity` components could be split up into a set of smaller components. Here are some reasons you would want to do this:
- Improve query performance by increasing parallelism and useful data in the CPU cache.
- More modular design can split code into smaller understandable pieces.
- Integrate with Bevy's change detection.
- Share data between client and Minecraft entity when they share the same ECS entity. (Typically the client will have a player entity associated with it).
- Save memory by spawning entities without unused components.

Some reasons you wouldn't want to do this:
- Many corner cases and interactions that are not accounted for can lead to bugs.
- Potentially confusing and unintuitive.
- Invalid states are very much representable.

---

| Component Name | Description | Effect When Added | Effect When Removed | Effect When Modified |
| -------------- | ----------- | -------------------------------- | ------------------------------------ | ---------------------- |
| `Despawned` | Any ECS Entities with this component are despawned at the end of the tick. This gives Valence an opportunity to perform deinitialization of components that can't be removed explicitly. In particular, `McEntity` and its other components. |  |  |
| `Client` | The main client component. Contains the TCP connection and packet buffers. Also contains immutable info such as username, UUID, and IP among other things.| Joins the client (Should only be done by Valence). Maybe we want to allow attaching `Client` to existing entities somehow? | No effect, but the client is disconnected when dropped. Removing only this component from an `McEntity` will allow you to take control. |  |
| `Disconnected` | Marker component to indicate that a client is disconnected. | | |
| `Location` | Contains the instance an Entity or Client is inside. Also contains the instance from the previous tick.  |  | Disallowed at least for entities because we need it to clean up the instance. | Changes the instance a client or entity is in. Makes clients respawn even if `old_instance == new_instance`. Can be used to respawn the client after death. |
| `Position` | The XYZ coordinates (old and new) of a client or entity. Automatically updated by Valence as a client moves around. | | Disallowed at least for entities because we need it to clean up the instance. | Teleports clients and entities when modified |
| `Direction` | Contains the pitch/yaw pair of an entity or client. Automatically updated by clients as they look around. | | Disallowed(?) | Sets the pitch/yaw of entities and teleports clients to set their pitch/yaw. Can be combined with `Position` modifications to form a single teleport. |
| `Velocity` | Contains the velocity vector for clients and entities. | | | Causes clients to be launched. Unknown effect on entities. (Velocity is really weird in Minecraft). |
| `OnGround` | The on ground boolean for clients and entities. Automatically updated by clients. | | | Changes the on ground state for entities. |
| `Vehicle` | The vehicle entity a client or entity is riding. | TODO | TODO | TODO |
| `DeathLocation` | Contains a `(DimensionId, BlockPos)` pair. Used by respawning clients to set their recovery compass position | | | Can be modified, but won't have an effect until the client is respawned. |
| `GameModeComponent` (`GameMode` was taken) | Contains the game mode of a client. | | Disallowed(?) | Sets the gamemode of the client it's attached to. |
| `McEntity` | The main component for Minecraft entities. Contains protocol entity ID and UUID. | Spawns the entity. Must have `Location` and `Position` to do so. Sets the protocol ID to the next unique value. Was initialized to zero when the component was created. | Definitely disallowed because we need the protocol ID to send despawn packets to clients. Also, we need the position+location to remove its ID from the instance it was in. Otherwise, there would be a memory leak.|
| `EntityKindComponent` (`EntityKind` was taken) | Contains the type of Minecraft entity (Blaze, Chicken, Player, etc). |  | Disallowed(?) | Respawns the entity as the new type. All metadata is reset. Protocol ID is reused(?) |
| `*Metadata`, where `*` is every entity type. Component and system definitions would be generated. | Contains the metadata (`TrackedData`) of a particular entity type. `TrackedData` is currently an enum, so this would save a lot of space. Not to mention easier because it's queryable and you wouldn't have to match on any enums. | Initializes the metadata. Would be nice if we allowed spawning entities without metadata to save memory. | Clears the metadata(?) | Updates the entity's metadata. Has no effect if component does not match the entity's type as determined by `EntityKindComponent`. When `PlayerMetadata` is modified on a client, the changes are sent to the client's own player entity. |
| `ExpOrbCount` | The amount of experience in an exp orb entity. Changes its visuals. | | | Only used when spawning exp orb entities. Modifications have no effect afterwards. |
| `FallingBlockState` | The `BlockState` of falling block entities | | | Only used when spawning falling block entities. Modifications have no effect afterwards. |
| `Statuses` | Bitset containing a bit for each entity status. Cleared at the end of the tick. | Triggers any set statuses for an entity. | | Triggers any set statuses for an entity. |
| `Animations` | Bitset containing a bit for each entity animation. Cleared at the end of the tick. | Triggers any set animations for an entity. | | Triggers any set animations for an entity. |
| `Hitbox` | Contains the AABB hitbox for an entity. Updated at the end of each tick. | | | No effect, but likely to be overwritten at the end of the tick. |

# Questions
- How granular should the components be? Should there be `Location`/`OldLocation` and `Position`/`OldPosition`, or is that kind of thing too cumbersome?
- What about miscellaneous data in `Client` like `is_hardcore`, `is_flat`, etc?
- Should UUID be shared between clients and entities as a component? Should it not be a component because it's immutable?
- Should the protocol ID of entities be a component? This would be immutable too.
- Should metadata components be broken up further to match Minecraft's class hierarchy? That seems very challenging.
- Working with metadata internally when there are a million different component types might be challenging. Probably need to cache metadata initialization bytes in `McEntity`.
- What about the inventory stuff for clients?
- What about poses?
- Does `McEntity` need to exist? It's kind of an ugly name.
- What is the most effective way to disallow removing components? Log an error? Panic in debug mode?

### PR DESCRIPTION
**Pull request by rj00a**
## Description

Divides the `Client` component into a set of smaller components as described by #199 (with many deviations). `McEntity` will be dealt with in a future PR.

- Divide `Client` into smaller components (There's a lot to look at).
- ~~Rename `McEntity` to `Actor` to avoid confusion between ECS entities and Minecraft entities.~~
- Move common components to `component` module.
- Remove `Username` type from `valence_protocol` because the added complexity wasn't adding much benefit.
- Clean up the inventory module.

I've stopped worrying about the "Effect When Added" and "Effect When Removed" behavior of components so much, and instead assume that all components of a particular thing are required unless otherwise stated.

Blocked on:
- [x] #264

## Test Plan

Steps:
1. Run examples and tests.

A large number of tweaks have been made to the inventory module. I tried to preserve semantics but I could have made a mistake there.

### CODE REVIEW

**Comment by dyc3** [comment]
I very much don't like renaming `McEntity` to `Actor`. I feel like the confusion between `Entity` and `McEntity` can be very easily remedied with proper doc comments. Do we really get questions/see confusion about it often?

**Comment by qualterz** [comment]
> I very much don't like renaming `McEntity` to `Actor`.

Yeah, `Actor` may sound too abstract but on the other hand `McEntity` too verbose.

**Comment by qualterz** [comment]
Maybe confusions should be avoided by leveraging namespaces like `mc::Entity` and `ecs::Entity`?

**Comment by dyc3** [comment]
`McEntity` is not too verbose. Using namespaces like that almost certainly makes the problem worse.

**Comment by AviiNL** [comment]
In my humble opinion, the valence project interfaces at least for a user to minecraft first, bevy last, so i would probably use `Entity` for a minecraft entity, and re-export the bevy entity to something like `BevyEntity`. Or have them both as `Entity` and leave it up to the user to qualify it, either with an `as` keyword in the `use` statement, or qualify in-line where needed.. point being, both are *entities*, so why not just call them that?

**Comment by qualterz** [comment]
Also, the invention of new terms would be better to avoid, because it's additional cognitive load for users of the framework.

**Comment by rj00a** [comment]
I'll just revert the `McEntity` -> `Actor` change.

> In my humble opinion, the valence project interfaces at least for a user to minecraft first, bevy last, so i would probably use `Entity` for a minecraft entity, and re-export the bevy entity to something like `BevyEntity`.

Not sure that's feasible with the way imports/exports work in Rust. We're re-exporting `bevy_app` and `bevy_ecs` at the root of `valence`, so the `BevyEntity` name would only be available in our prelude? But then we wouldn't be able re-export the bevy prelude in our prelude easily without something like Haskell's `hiding`.

> Or have them both as Entity and leave it up to the user to qualify it

That would make using `valence::prelude` unpleasant IMO.

**Comment by dyc3** [comment]
I'm getting some ridiculous rubber banding when running all of the examples. The packet inspector shows really big client bound packets at regular intervals. I think that chunks keep getting sent to the client when they aren't needed? Not really sure

**Comment by rj00a** [comment]
> I'm getting some ridiculous rubber banding when running all of the examples.

This is caused by modifications to player position, yaw, pitch, in the packet handler triggering change detection for those components. A system later picks up on those changes and sends a teleport packet.

One solution is to bypass change detection in the packet handler. I'm not entirely happy with that because it can lead to surprising behavior when using `Changed<Position>` in user code. We have no way to distinguish changes made by valence and changes made by users.

**Comment by dyc3** [comment]
I concur, I think option 3 seems best.

**Pull request merged**
