### PR TITLE
fix clippy

### PR DESCRIPTION
**Pull request by JackCrumpLeys**
make clippy happy.

### CODE REVIEW

**Comment by JackCrumpLeys** [comment]
I need to do a lil more

**Comment by JackCrumpLeys** [comment]
ive done what I can as generated code is failing CI and I dont wanna fix that rn

**Review by rj00a — APPROVED** [review]
Wish there was a way to disable the `pub` -> `pub(crate)` lint for binaries.

**Comment by JackCrumpLeys** [comment]
@rj00a I'm gonna work on the dep update now so can we get this merged? I know it doesn't solve all but I can do the generated code after updating deps.

**Pull request merged**
