### PR TITLE
Add clippy linting and formatting validation to GitHub actions workflow

### PR DESCRIPTION
**Pull request by CatDevz**
Fixes issue #16 by failing the workflow if clippy lints dont pass or formatting is incorrect.

### CODE REVIEW

**Comment by rj00a** [comment]
I would like to avoid boxing the `Text` to fix the clippy issue. Fixing #18 should resolve that.

**Review by rj00a — CHANGES_REQUESTED** [review]
I would like to avoid boxing the `Text` to fix the clippy issue. Fixing #18 should resolve that. In the meantime you can tell clippy to ignore it.

Also I don't believe `cargo clippy` will tell you about broken docs so this doesn't fully resolve #16.

**Comment by dyc3** [comment]
Adding another step for `cargo test --doc` should give us signal about broken docs. It needs to be another step because the `--doc` arg makes cargo test _only_ the docs, and it skips the normal unit tests.

**Comment by rj00a** [comment]
Closing in favor of #46

**Pull request closed without merging**
