### PR TITLE
Criterion to divan

### PR DESCRIPTION
**Pull request by JackCrumpLeys**
As discussed in #620.

### CODE REVIEW

**Review by rj00a — APPROVED** [review]

**Comment by rj00a** [comment]
Should be good once conflicts are fixed.

**Comment by JackCrumpLeys** [comment]
> Should be good once conflicts are fixed.

I can't fix those (not admin) I suggest you  just accept mine for all conflicts as the conflicts are only in the benchmark files which are completely changed anyway.

**Comment by rj00a** [comment]
Your branch is 5 commits behind the main branch. If you rebase or merge you can resolve the conflicts locally.

**Comment by JackCrumpLeys** [comment]
Ok will do.

**Comment by JackCrumpLeys** [comment]
Well apparently main branch has failing CI so it is not my fault.

**Comment by rj00a** [comment]
Yeah don't worry about CI for now. Thanks.

**Comment by JackCrumpLeys** [comment]
> Yeah don't worry about CI for now. Thanks.

made clippy happy in #623

**Pull request merged**
