### PR TITLE
Add sample players when client requests ping list

### PR DESCRIPTION
**Pull request by alice39**
This will allow to set any sample players with
custom names and ids, also it is possible to set
\u00A7 character to have colorful text

By the way, I'm kinda new to Rust, so any suggestion in this code would be amazing to keep improving

### CODE REVIEW

**Comment by dyc3** [comment]
Hey, thanks for the PR! Would you mind including some instructions for how to test this? I tried loading up cow_sphere and pressing tab to see the player list and didn't see any custom text.

**Comment by alice39** [comment]
Oh, that's not in the server but I'm the server list, I think the title is confusing a bit

**Review by dyc3 — APPROVED** [review]
LGTM

**Comment by rj00a** [comment]
After reviewing your PR I decided that most things would need to be changed. I've gone and done that in #47. Maybe you can take a look. Sorry about that.

**Comment by alice39** [comment]
Ooh don't worry about it, your PR is even better what I had done, including docs, the mine were kind of ambiguous

**Pull request closed without merging**
